***One Hot Encoding***

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

data = np.array([['Red', 'Blue', 'Green', 'Red', 'Blue']])

# Convert shape from (1, 5) to (5, 1)
data = data.reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)

encoder_data = encoder.fit_transform(data)

print(encoder_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


**Bag of Words(BOW)**

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I love AI",
    "I love Python",
    "Python is powerful"
    "I had had a cow"
]

vectorizer = CountVectorizer()

bow = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(bow.toarray())

['ai' 'cow' 'had' 'is' 'love' 'powerfuli' 'python']
[[1 0 0 0 1 0 0]
 [0 0 0 0 1 0 1]
 [0 1 2 1 0 1 1]]


**N-Grams**

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

sentence = ["I love machine learning"]

# Bigram
vectorizer = CountVectorizer(ngram_range=(2, 2))

ngrams = vectorizer.fit_transform(sentence)

print(vectorizer.get_feature_names_out())

['love machine' 'machine learning']


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

sentence = ["I love machine learning"]

vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    token_pattern=r'(?u)\b\w+\b'  # Token_pattern
)

ngrams = vectorizer.fit_transform(sentence)

print(vectorizer.get_feature_names_out())

['i love' 'love machine' 'machine learning']


In [15]:
# Trigram  → 3 words

from sklearn.feature_extraction.text import CountVectorizer

sentence = ["I love machine learning and I also Love Python Language"]

vectorizer = CountVectorizer(ngram_range=(3, 3))

ngrams = vectorizer.fit_transform(sentence)

print(vectorizer.get_feature_names_out())


['also love python' 'and also love' 'learning and also'
 'love machine learning' 'love python language' 'machine learning and']


***TF-IDF (Term Frequency – Inverse Document Frequency)***

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentences = [
    "I love Python",
    "I love machine learning",
    "Python is powerful"
]

vectorizer = TfidfVectorizer()

tfidf = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(tfidf.toarray())

['is' 'learning' 'love' 'machine' 'powerful' 'python']
[[0.         0.         0.70710678 0.         0.         0.70710678]
 [0.         0.62276601 0.4736296  0.62276601 0.         0.        ]
 [0.62276601 0.         0.         0.         0.62276601 0.4736296 ]]


**Word2Vec**

In [18]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 72.5 MB/s eta 0:00:00


In [19]:
from gensim.models import Word2Vec

sentences = [
    ["I", "love", "machine", "learning"],
    ["I", "love", "deep", "learning"],
    ["machine", "learning", "is", "powerful"]
]

model = Word2Vec(
    sentences,
    vector_size=100,
    window=2,
    min_count=1,
    sg=1
)

# Get vector
print(model.wv["learning"])

# Find similar words
print(model.wv.most_similar("learning"))

[-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.46979